name: Labeling new issue
on:
  issues:
      types: ['opened', 'edited']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Renato66/auto-label@v2 # or v2.2.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          ignore-comments: false
          labels-not-allowed: '["wontfix","question","invalid"]'
