blank_issues_enabled: true

contact_links:
  - name: Godot game
    url: https://github.com/godotengine/godot-proposals
    about: Please submit feature proposals on the Godot proposals repository, not here.

  - name: Godot exported games
    url: https://github.com/godotengine/godot-docs
    about: Please report issues with documentation on the Godot documentation repository, not here.

  - name: Godot community channels
    url: https://github.com/godotengine
    about: Please ask for technical support on one of the other community channels, not here.
