name: Labeling new issue
on:
  issues:
      types: ['opened', 'edited']
  issue_comment:
    types: [created, edited]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Renato66/auto-label@v2 # or v2.2.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          labels-synonyms: '{"bug":["error","need fix","not working"],"wontfix":["no fix"],"enhancement":["upgrade"],"question":["help"]}'
          labels-not-allowed: '["good first issue"]'
          default-labels: '["! not seen !"]'
